language: python
python:
- 3.6
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: asleao-github
    token:
      secure: "$SONAR_TOKEN"
    branches:
    - master
install:
- pip install -r requirements.txt
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: heroku
  api_key:
    secure: QNPZPxroFLAl2FKuXIGpct3xE3/V+mK+mhLufimICn8odDtOCEOZrnNHaV1Y9xHFY/9/RMzYvMqElG+8QGhKIJInAYtcCFq7+v0GLzxOSsR4AzQX2m4FApCO+M54Upwl2+c4E3NejLOL5Q3/BwhAOAWAz/w1sHN4fdlhtNSIhrtWsTHRgQF/L9lxovt6ojDukEwyamjMe//smxbQzhrP378zhascG5Hkp0rhqf24ApA/lMtutMoz6WONqIKAyOifSJiX9lsCH/nnV3e/bLF9x9IzO8r4CjIBUXtWTucEENNFB+VuGXdHchSmJbGfcseIRXM2tehn6431QsqMirAMJJiNhqPB+2o/on9dmQMA/WH2lBfLXo18eEU/44o9+rksdiEbtZ6Z1Uwj2tWaJIsMyiQQn7THlu9j/SCC8y0smhl2agZ/f02qIxr+22DTcSe1Ywmy+87aq0njiu+nGowr5vZO1Buz53CsBaVaOt9FRgNbduTFdD1SYdz+3JNlH5SZjJcgEphk1cNiM5yTdpEL64QX24Sd5tIFi8+09qHtvRueFQdgGrJISlnpK5TUPq/5zX9mlitGWv9qdxdwPRtbRjW7NaVFQ073a/QIq6KpFPZdswI1Vbgah0GLXk6X5+5uijklKcF693YHj4VbbszjpQHXRUJZR0+ADI20y7haHF4=
  app: github-adapter
  on:
    repo: asleao/github-adapter